# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emax6_0_0/design_1_emax6_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_emax6_0_0 || ORIG_REF_NAME==design_1_emax6_0_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_emax6_0_0/src/fpga_bram128/fpga_bram128.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_bram128 || ORIG_REF_NAME==fpga_bram128} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# Block Designs: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_emax6_0_0/src/fpga_bram128/fpga_bram128_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_arsw_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_rsw_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_awsw_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_wsw_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_bsw_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_s00a2s_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sarn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_srn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sawn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_swn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_sbn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_s01a2s_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_sarn_1_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_srn_1_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_sawn_1_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_swn_1_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_sbn_1_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m00s2a_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m00arn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m00rn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m00awn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00wn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m00bn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/ZCU102-step4000/ZCU102_8st.gen/sources_1/bd/design_1/design_1_ooc.xdc
