# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_smc_0/design_2_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_smc_0 || ORIG_REF_NAME==design_2_axi_smc_0} -quiet] -quiet

# Block Designs: bd/design_2/ip/design_2_axi_smc_0/bd_0/bd_ebcc.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_0/bd_ebcc_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_2/bd_ebcc_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_3/bd_ebcc_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_4/bd_ebcc_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_5/bd_ebcc_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_6/bd_ebcc_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_7/bd_ebcc_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_8/bd_ebcc_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_9/bd_ebcc_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_10/bd_ebcc_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_11/bd_ebcc_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_12/bd_ebcc_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_13/bd_ebcc_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_14/bd_ebcc_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_15/bd_ebcc_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_16/bd_ebcc_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_17/bd_ebcc_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_18/bd_ebcc_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_19/bd_ebcc_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_20/bd_ebcc_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_21/bd_ebcc_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_22/bd_ebcc_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_23/bd_ebcc_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_24/bd_ebcc_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_25/bd_ebcc_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_26/bd_ebcc_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_27/bd_ebcc_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_28/bd_ebcc_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_29/bd_ebcc_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_30/bd_ebcc_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_31/bd_ebcc_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_32/bd_ebcc_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_33/bd_ebcc_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_emax6_0_0/design_2_emax6_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_emax6_0_0 || ORIG_REF_NAME==design_2_emax6_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_emax6_0_0/src/fpga_bram128/fpga_bram128.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_bram128 || ORIG_REF_NAME==fpga_bram128} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_200M_0/design_2_rst_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rst_200M_0 || ORIG_REF_NAME==design_2_rst_200M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_300MHz_0/design_2_rst_300MHz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rst_300MHz_0 || ORIG_REF_NAME==design_2_rst_300MHz_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_zynq_ultra_ps_e_0_0/design_2_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_2_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: bd/design_2/ip/design_2_axi_smc_0/ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_2/bd_ebcc_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_2/bd_ebcc_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_3/bd_ebcc_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_3/bd_ebcc_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_4/bd_ebcc_arsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_5/bd_ebcc_rsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_6/bd_ebcc_awsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_7/bd_ebcc_wsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_8/bd_ebcc_bsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_12/bd_ebcc_s00a2s_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_13/bd_ebcc_sarn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_14/bd_ebcc_srn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_15/bd_ebcc_sawn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_16/bd_ebcc_swn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_17/bd_ebcc_sbn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_21/bd_ebcc_s01a2s_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_22/bd_ebcc_sarn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_23/bd_ebcc_srn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_24/bd_ebcc_sawn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_25/bd_ebcc_swn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_26/bd_ebcc_sbn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_27/bd_ebcc_m00s2a_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_28/bd_ebcc_m00arn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_29/bd_ebcc_m00rn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_30/bd_ebcc_m00awn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_31/bd_ebcc_m00wn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_32/bd_ebcc_m00bn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_emax6_0_0/src/fpga_bram128/fpga_bram128_ooc.xdc

# XDC: bd/design_2/ip/design_2_rst_200M_0/design_2_rst_200M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_200M_0 || ORIG_REF_NAME==design_2_rst_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_rst_200M_0/design_2_rst_200M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_200M_0 || ORIG_REF_NAME==design_2_rst_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_rst_300MHz_0/design_2_rst_300MHz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_300MHz_0 || ORIG_REF_NAME==design_2_rst_300MHz_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_rst_300MHz_0/design_2_rst_300MHz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_300MHz_0 || ORIG_REF_NAME==design_2_rst_300MHz_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_zynq_ultra_ps_e_0_0/design_2_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_zynq_ultra_ps_e_0_0/design_2_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_2_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
